-   id: add-trailing-comma
    name: Add trailing commas
    description: Automatically add trailing commas to calls and literals.
    entry: add-trailing-comma
    language: python
    types: [python, pyi]
